name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21' # یا نسخه مورد نظر شما

      - name: Build with Maven
        run: mvn package

      - name: Run the application
        run: |
          java -jar ./target/server-0.0.1-SNAPSHOT.jar up
