name: ci-cd

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Create application.yml
      run: |
        echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application-product.yml

    - name: Build with Maven
      run: mvn clean install
