name: ci-cd

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -U
        working-directory: /home/ali/carbon-backend/_work/Carbon-backend/Carbon-backend

      - name: Restart application with PM2
        run: |
          pm2 delete zilanmod-server || true
          pm2 start "java -jar target/*.jar --spring.profiles.active=product" --name zilanmod-server
        working-directory: /home/ali/carbon-backend/_work/Carbon-backend/Carbon-backend

